version: '3'

services:
  db:
    image: postgres
    volumes:
      - ./database:/var/lib/postgresql/data
    #Uncomment to diagnose DB from host IDE
    #ports: "5432:5432"
  web:
    build: .
    command:
      - /bin/sh
      - -c
      - |
        /config/docker_entrypoint.py
        python3 manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    volumes:
      - ./application:/code
    depends_on:
      - db
